### ISSUE TITLE
Attempted to create command "invoke" without usage or description.

### ISSUE THREAD

**Issue by Falkor** [lastobelus/cleanthor#2]
I receive the following warning on all invokation of `cleanthor` on Ruby 2.1.0: 

``` sh
$> bundle exec bin/cleanthor -T
[WARNING] Attempted to create command "invoke" without usage or description. Call desc if you want this method to be available as command or declare it inside a no_commands{} block. Invoked from "/private/tmp/cleanthor/lib/cleanthor/thor/task.rb:5:in `<class:Task>'".
garden
------
cleanthor garden:work:weed  # weed the garden

work
----
cleanthor work:shovel  # shovels stuff
```

``` sh
$> ruby --version
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]
```

That looks minor of course, yet my attempts to add the `desc` to the `invoke` function of `lib/cleanthor/thor/task.rb` failed so far with the message 

```
~/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:534:in `is_thor_reserved_word?': "invoke" is a Thor reserved word and cannot be defined as command (RuntimeError)
```

**Comment by flyinbutrs** [comment]
I see the same issue...  any luck fixing this?

**Comment by dgorack** [comment]
Added a pull request that fixes the warning: #3 
Hope that helps.
